name = "Andamio-Platform/plumbline-global-state"
version = "2.0.0-alpha.1"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts used by the andamio protocol."

[repository]
user = "Andamio-Platform"
project = "plumbline-global-state"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
